### 1. Topological Spaces 🔷

Foundational concepts in point-set topology.

#### What You'll Learn
- Definition of topological spaces
- Continuous functions in topological settings
- Homeomorphisms and topological invariants
- Separation axioms (T₀, T₁, T₂, etc.)

#### Core Concepts

A **topological space** is a pair (X, τ) where:
- X is a set
- τ is a collection of subsets (topology) satisfying:
  1. ∅ and X are in τ
  2. Arbitrary unions of sets in τ are in τ
  3. Finite intersections of sets in τ are in τ

#### Example

\`\`\`julia
# Discrete topology: all subsets are open
discrete_topology = "All 2^n subsets are open"

# Trivial topology: only ∅ and X are open
trivial_topology = "Minimal separation"

# Standard topology on ℝ: basis of open intervals
standard_topology = "Generated by open intervals (a,b)"
\`\`\`

#### Key Theorems
- Continuous image of compact space is compact
- Connected spaces
- Path connectivity

#### Applications
- Modern geometry and physics
- Data topology and manifold learning
- Algebraic topology

---

**Next Chapter**: [Manifolds](./02_manifolds.jl)
